name: dnd-board-cd
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      
      - name: Install Dependencies
        run: npm install

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Build
        run: npm run build

      - name: Test
        run: ng test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist/apps/dnd-board

